### ISSUE TITLE
Zoom Single Class Documentation missing expire time.

### ISSUE THREAD

**Issue by git-bhanu** [Krenovate-Solutions-Pvt-Ltd/CFI#18]
[Zoom Single Class documentation](https://krenovate-solutions-pvt-ltd.github.io/CFI/Zoom-Single-Class/)  page should also have a section which tells about 

- The time at which the card stops showing on the dashboard of the Customer.

This should also be added to Pre-Recorded Single Class

@puni2112 @manjeetkaur24

**Comment by manjeetkaur24** [comment]
The changes have been made. Pls go thru and let me know.

I have done a pull and push request. Merge and let me know

**Comment by git-bhanu** [comment]
Changes look good to me. 

It will be updated on the website when @puni2112 will merge the next time.
I am not closing this issue. We will close it once the merge is done.

Commit related to the issue: https://github.com/Krenovate-Solutions-Pvt-Ltd/CFI/commit/b8522a553295dc5a02206ced90a55911b47ceec4

**Comment by puni2112** [comment]
Merged, Pushed and merged back into your branch @Manjeet Kaur
<manjeet@krenovate.com>

@Bhanu Kumar Singh <bhanu@krenovate.com> Please check live and close the
issue.

Thanks

Puneet Sharma
Director
Krenovate Solutions Pvt Ltd
https://www.krenovate.com
9999333966
